### ISSUE TITLE
%1.1 Summary: Follow

### ISSUE THREAD

**Issue by danglotb** [danglotb/skillful_network#5]
For task %1 we want to add to the skillful network the feature of Follow. As on Twitter, the user can follow other users: candidate, students, companies, trainers, etc...

Discuss here how to integrate this new feature to the platform. 
- What are the core functionalities?
- Have you any ideas or suggestions to enhance this feature?

**Comment by danglotb** [comment]
- Notifications when new content is added (configuration)

**Comment by pfouque06** [comment]
### Diagramme de classe V1.4 - Follow State Tracker:

[diagramme.classes.folllowers.V1.4.pdf](https://github.com/danglotb/skillful_network/files/4830242/diagramme.classes.folllowers.V1.4.pdf)

**Comment by danglotb** [comment]
LGTM, nice work! Thank you.
