### ISSUE TITLE
%3.1 Summary: Identification

### ISSUE THREAD

**Issue by danglotb** [danglotb/skillful_network#7]
For task %3 we want to refactor the way that the users are identified. We want to go back to the original requirements: not having a password but rather a temporary code generated at each identification. With cookies and sessions, the user won't have to identified itself each time.

Discuss here how to integrate this new feature to the platform.

What are the core functionalities?
Have you any ideas or suggestions to enhance this feature?

**Comment by danglotb** [comment]
Linked to #19

**Comment by danglotb** [comment]
See another way of authentification with Facebook / Google, etc...

**Comment by anaKnell** [comment]
**Authentification exemple: case basic Email and case Social media**
![Capture d’écran 2020-06-24 à 12 05 58](https://user-images.githubusercontent.com/13932840/85536267-3bac4180-b613-11ea-903d-e41ef179aab3.png)
![Capture d’écran 2020-06-24 à 12 05 22](https://user-images.githubusercontent.com/13932840/85536284-3fd85f00-b613-11ea-9460-5f1d7576582c.png)
